FROM gradle AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle build --no-daemon 

FROM openjdk

EXPOSE 8080

RUN mkdir /app

COPY --from=build /home/gradle/src/build/libs/SpotifySegrator-1.0-SNAPSHOT.jar /app/SpotifySegrator-1.0-SNAPSHOT.jar

ENTRYPOINT ["java", "-XX:+UnlockExperimentalVMOptions", "-Djava.security.egd=file:/dev/./urandom","-jar","/app/SpotifySegrator-1.0-SNAPSHOT.jar"] #when the virtual machine start this the comment thts get runned